import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MenuBar } from '@/components/menu-bar';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useState } from 'react';
import Providers from '@/context/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<MenuBar />
					<div className="mx-12 mt-12">{children}</div>
				</Providers>
			</body>
		</html>
	);
}
