import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MenuBar } from '@/components/menu-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MenuBar />
				<div className="mx-12 mt-12">{children}</div>
			</body>
		</html>
	);
}
